=== PandiPanda69/GHome/src/ia/rules.dtd
<!DOCTYPE rules [

<!ELEMENT rules (rule+)>
<!ELEMENT rule (actions,conditions)>
<!ELEMENT actions (activate,alert)>
<!ELEMENT conditions (condition)>
<!ELEMENT activate (#PCDATA)>
<!ELEMENT alert (#PCDATA)>
<!ELEMENT condition (#PCDATA)>

<!ATTLIST rule name CDATA #REQUIRED>
<!ATTLIST activate devide CDATA #REQUIRED>
<!ATTLIST alert recipient CDATA #REQUIRED>
<!ATTLIST condition device CDATA #REQUIRED>
<!ATTLIST condition field CDATA #REQUIRED>
<!ATTLIST condition type CDATA #REQUIRED>

]>

=== PandiPanda69/GHome/src/ia/rules.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE rules SYSTEM "rules.dtd">

<rules>
	<rule name="Chauffage chambre">
		<actions>
			<activate device="alim_chauffage" field="BUTTON_3">false</activate>
			<alert recipient="web">Chauffage mis hors tension pour éviter le gaspillage d’énergie.</alert>
		</actions>
		<conditions>
			<condition device="temp_12" field="TEMPERATURE" type="sup">1.2</condition>
			<condition device="button_05" field="BUTTON_1" type="equ">true</condition>
			<condition device="button_05" field="BUTTON_2" type="equ">false</condition>
		</conditions>
	</rule>
</rules>
